//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NicksPowerTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NicksPowerTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap HelloWorld {
            get {
                object obj = ResourceManager.GetObject("HelloWorld", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;one:Page xmlns:one=&quot;http://schemas.microsoft.com/office/onenote/2010/onenote&quot; ID=&quot;{00E65221-3F2E-41E7-86F8-34E68CB19121}{1}{B0}&quot; name=&quot;Presentation: Cerebrum: Thalamus and Cortex&quot; dateTime=&quot;2011-05-08T19:12:15.000Z&quot; lastModifiedTime=&quot;2011-05-18T02:30:46.000Z&quot; pageLevel=&quot;2&quot; isCurrentlyViewed=&quot;true&quot; lang=&quot;en-US&quot;&gt;
        ///  &lt;one:TagDef index=&quot;0&quot; type=&quot;0&quot; symbol=&quot;82&quot; fontColor=&quot;automatic&quot; highlightColor=&quot;#FFFF00&quot; name=&quot;Important&quot; /&gt;
        ///  &lt;one:TagDef index=&quot;1&quot; type=&quot;1&quot; symbol=&quot;59 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LargePage {
            get {
                return ResourceManager.GetString("LargePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt; 
        ///.
        /// </summary>
        internal static string LinkedNotes {
            get {
                return ResourceManager.GetString("LinkedNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;customUI xmlns=&quot;http://schemas.microsoft.com/office/2006/01/customui&quot; loadImage=&quot;GetImage&quot;&gt;
        ///	&lt;ribbon&gt;
        ///		&lt;tabs&gt;
        ///			&lt;tab id=&quot;tabCustom&quot; label=&quot;Custom&quot;&gt;
        ///				&lt;group id=&quot;groupHello&quot; label=&quot;Hello&quot;&gt;
        ///					&lt;button id=&quot;buttonHello&quot; label=&quot;Hello World!&quot; size=&quot;large&quot; screentip=&quot;Press this for a &apos;Hello World&apos; message&quot; onAction=&quot;showHello&quot; image=&quot;HelloWorld.png&quot;/&gt;
        ///				&lt;/group&gt;
        ///			&lt;/tab&gt;
        ///		&lt;/tabs&gt;
        ///	&lt;/ribbon&gt;
        ///&lt;/customUI&gt;.
        /// </summary>
        internal static string ribbon {
            get {
                return ResourceManager.GetString("ribbon", resourceCulture);
            }
        }
    }
}
